services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - DB_URL=${DB_URL}         # <--- add this
    ports:
      - "4000:4000"

  # ---- disable Mistral for now ----
  # mistral_7b:
  #   build:
  #     context: ./backend/llms/mistral_7b
  #   platform: linux/arm64/v8
  #   container_name: mistral_7b_llm
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./backend/llms/mistral_7b/model:/model

  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "8000:5432"  # host:container

volumes:
  pgdata:
