services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:4000"


  mistral_7b:
    build:
      context: ./backend/llms/mistral_7b
    platform: linux/arm64/v8
    container_name: mistral_7b_llm
    ports:
      - "8080:8080"
    volumes:
      - ./backend/llms/mistral_7b/model:/model